/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package BooleanFunctionsTT;
import java.awt.Container;
import java.util.*;
/**
 *
 * @author wllmNunez
 */
public class MmodificateBF extends javax.swing.JDialog {

    /**
     * Creates new form MmodificateBF
     */
    
    public MmodificateBF(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    javax.swing.JTable jTable1;
    private int grado;
    private String funcion;
    public String getFuncion()
    {
        return this.funcion;
    }
    public MmodificateBF(java.awt.Frame parent, boolean modal, int degree, String booleanFunction) {
        super(parent, modal);
        initComponents();
        int pixelPCelda=25;
        this.setSize((degree+1)*pixelPCelda+100, this.getHeight());
        this.grado=degree;
        this.funcion=booleanFunction;
        Aniquiladores2 an=new Aniquiladores2();
        jTable1 = new javax.swing.JTable();
        List<String> trueTable=an.getListTrueTable(this.grado);
        Object[][] thaoFuncion=new Object[(int)Math.pow(2, grado)][grado+1];
        String sCeros="";
        for(int i=0;i<this.grado;i++)
        {
            sCeros+="0";
        }
        String newThao="";
        int contadorFila=0;
        for(String sThao:trueTable)
        {
            int longitudThao=sThao.length();
            newThao=sCeros.substring(0,this.grado-longitudThao)+sThao+((this.funcion.length()>contadorFila)?this.funcion.substring(contadorFila, contadorFila+1):"0");
            String[] itemThao=newThao.split("|");
            for(int j=1;j<itemThao.length;j++){
                    thaoFuncion[contadorFila][j-1]=itemThao[j];
                    }
            contadorFila++;
        }
        String titles="";
        final boolean[] canEdit=new boolean[this.grado+1];
        for(int i=1;i<=this.grado;i++)
        {
            titles+="x"+i+"|";
            canEdit[i-1]=false;
        }
         canEdit[this.grado]=true;
         titles+="f";
         String[] names=titles.split("\\|");
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
           thaoFuncion,names
        ){ 
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        /*
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },names
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
         );
         */
        //this.panelArea.add(jTable1);
         panelArea.setViewportView(jTable1);
    }
    private void createFila(String booleanValue)
    {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelArea = new javax.swing.JScrollPane();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edición");
        setMinimumSize(new java.awt.Dimension(256, 256));

        jLabel1.setText("Modificacion de funcion Booleana");

        panelArea.setMinimumSize(new java.awt.Dimension(200, 150));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addComponent(panelArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelArea, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String newFunction="";
        for(int i=0;i<(int)Math.pow(2, this.grado);i++)
        {
            String value=(String)jTable1.getValueAt(i,this.grado);
            newFunction+=(!value.equals(""))?value:"0";
        }
        this.funcion=newFunction;
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmodificateBF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmodificateBF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmodificateBF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmodificateBF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmodificateBF dialog = new MmodificateBF(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane panelArea;
    // End of variables declaration//GEN-END:variables
}
